"""Add departure_time and arrival_time to flights

Revision ID: 6c9427c35bc9
Revises: 6b55ef4ebe81
Create Date: 2024-08-07 11:36:07.335675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Time

# revision identifiers, used by Alembic.
revision = '6c9427c35bc9'
down_revision = '6b55ef4ebe81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('arrival_time', sa.Time(), nullable=True))

    # Populate the new columns with default values (e.g., 10:00 for departure_time and 11:00 for arrival_time)
    flight_table = table('flights',
                         column('departure_time', sa.Time()),
                         column('arrival_time', sa.Time()))
    
    op.execute(
        flight_table.update().values(departure_time=sa.text("'10:00'"), arrival_time=sa.text("'11:00'"))
    )

    # Alter the columns to be non-nullable
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('departure_time', existing_type=sa.Time(), nullable=False)
        batch_op.alter_column('arrival_time', existing_type=sa.Time(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('departure_time')
    # ### end Alembic commands ###
