"""Add trip_type to flights

Revision ID: 77b122d88e65
Revises: 6c9427c35bc9
Create Date: 2024-08-09 08:47:39.660925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b122d88e65'
down_revision = '6c9427c35bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        # Adding the column with a default value to avoid the SQLite NOT NULL constraint error
        batch_op.add_column(sa.Column('trip_type', sa.String(length=10), nullable=False, server_default='one-way'))

    # Remove the server_default after the column is added (optional)
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('trip_type', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('trip_type')
    # ### end Alembic commands ###
